### ISSUE TITLE
Work without translator

### ISSUE THREAD

**Issue by bohdank** [Kdyby/Validator#14]
We want to use e-mail validation. Is it possible to use Kdyby\Validator without implementing Symfony\Component\Translation\TranslatorInterface?

```
exception 'Nette\DI\ServiceCreationException' with message 'Service of type Symfony\Component\Translation\TranslatorInterface needed by Symfony\Component\Validator\Context\ExecutionContextFactory::__construct() not found. Did you register it in configuration file?' in /var/www/project/vendor/nette/di/src/DI/Helpers.php:107
Stack trace:
#0 /var/www/project/vendor/nette/di/src/DI/ContainerBuilder.php(704): Nette\DI\Helpers::autowireArguments(Object(ReflectionMethod), Array, Object(Nette\DI\ContainerBuilder))
#1 /var/www/project/vendor/nette/di/src/DI/ContainerBuilder.php(607): Nette\DI\ContainerBuilder->formatStatement(Object(Nette\DI\Statement))
#2 /var/www/project/vendor/nette/di/src/DI/ContainerBuilder.php(571): Nette\DI\ContainerBuilder->generateService('validator.conte...')
#3 /var/www/project/vendor/nette/di/src/DI/Compiler.php(206): Nette\DI\ContainerBuilder->generateClasses(NULL, NULL)
#4 /var/www/project/vendor/nette/di/src/DI/Compiler.php(139): Nette\DI\Compiler->generateCode(NULL, NULL)
#5 /var/www/project/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(266): Nette\DI\Compiler->compile()
#6 [internal function]: Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#7 /var/www/project/vendor/nette/di/src/DI/ContainerLoader.php(111): call_user_func_array(Array, Array)
#8 /var/www/project/vendor/nette/di/src/DI/ContainerLoader.php(76): Nette\DI\ContainerLoader->generate('Container_51c84...', Array)
#9 /var/www/project/vendor/nette/di/src/DI/ContainerLoader.php(41): Nette\DI\ContainerLoader->loadFile('Container_51c84...', Array)
#10 /var/www/project/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(221): Nette\DI\ContainerLoader->load(Array, Array)
#11 /var/www/project/app/bootstrap.php(14): Nette\Configurator->createContainer()
#12 /var/www/project/index.php(3): require('/var/www/projec...')
#13 {main}
```

**Comment by enumag** [comment]
Symfony/Validator itself [requires](https://github.com/symfony/Validator/blob/master/composer.json#L20) Symfony/Translation so probably not.

**Comment by bohdank** [comment]
@enumag :+1: 

We really want to use Nette e-mail validation, but we need it in Doctrine annotation. Is there any different way how to do that?

**Comment by enumag** [comment]
If you want to also validate other things than e-mail then just use Validator + Translation. If e-mail is the only thing I would recommend you to either avoid using annotations, or just create your own annotation class for it.

**Comment by bohdank** [comment]
@enumag Thanks a lot.
